############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
name = "Curricula"
url = "/curricula"
weight = 3

[[main]]
name = "Applications"
url = "/applications"
weight = 3

[[main]]
weight = 4
name = "Resources"

[[main]]
parent = "Resources"
name = "Casual CTF"
url = "/casualCTF"

[[main]]
parent = "Resources"
name = "Mentors"
url = "/mentors"

[[main]]
parent = "Resources"
name = "Interns"
url = "/interns"

[[main]]
parent = "Resources"
name = "Opportunities"
url = "/opportunities"

[[main]]
parent = "Resources"
name = "Peer Mentors"
url = "/peer-mentors"

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Applications"
url = "/applications"
weight = 2

[[footer]]
name = "Curricula"
url = "/curricula"
weight = 2

[[footer]]
name = "Scholar's LMS"
url = "https://viceroydecree.moodlecloud.com/"
weight = 2
